[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Patch in perma debuff for solar flare
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability and self.ability.perma_debuff then self.debuff = true end'''
position = 'after'
payload = '''
if self.actually_permanent_debuff then self.debuff = true end'''
match_indent = true
