[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)

local modded = false
'''
position = "after"
payload = '''
local junks = 0
for i, v in pairs(scoring_hand) do
    if v.config.center.key == "m_worm_junk_card" then junks = junks + 1 end
end
G.GAME.junk_hands_mult = G.GAME.junk_hands_mult or 1.5
local junk_hands_mult = G.GAME.junk_hands_mult ^ junks
mult = mult * junk_hands_mult
hand_chips = hand_chips * junk_hands_mult
update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
                                    delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = mult, chips = hand_chips})
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
                delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
'''
position = "at"
payload = '''

'''
match_indent = true