[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

# Each active poptart gets its update function called, if it has one
[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''
if G.STAGE == G.STAGES.RUN then
'''
position = "before"
payload = '''
if self.ability.meow_poptarts then
    for _, poptart in ipairs(self.ability.meow_poptarts) do
        local obj = G.P_CENTERS[poptart.key] or {}
        if obj.nyan_update and type(obj.nyan_update) == 'function' then
            obj:nyan_update(poptart, self, dt)
        end
    end
end
'''
match_indent = true