[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "love.graphics.draw(last_canvas, 0, 0)"
position = "after"
payload = '''
if shader.key == "worm_util_test" and Wormhole.util_els then
	local scale = G.TILESIZE*G.TILESCALE*G.CANV_SCALE
	for k,v in ipairs(Wormhole.util_els) do
		love.graphics.push()
		love.graphics.setShader()
		G.OVERLAY_TUTORIAL = true
		v:translate_container()
		v:draw()
		G.OVERLAY_TUTORIAL = nil
		love.graphics.pop()
	end
end
'''
match_indent = true
times = 1

