[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Prevent "BUY AND USE" button on Drinks in shop
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''return base_background'''
position = "before"
payload = '''
if card.area == G.shop_jokers and G.shop_jokers then
  if card.ability.consumeable and card.ability.set == "abs_drinks"  then
    base_attach.children.buy_and_use = nil
  end
  base_attach.children.buy = G.UIDEF.card_focus_button{
    card = card, parent = base_attach, type = 'buy',
    func = 'can_buy', button = 'buy_from_shop', card_width = card_width, buy_and_use = buy_and_use
  }
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
SMODS.calculate_context({using_consumeable = true, consumeable = card, area = card.from_area})
'''
position = 'at'
payload = '''
if card.ability.set ~= 'abs_drinks' then
  SMODS.calculate_context({using_consumeable = true, consumeable = card, area = card.from_area})
end
'''
match_indent = true
